### ISSUE TITLE
Not finding matching users known to Moodle (LDAP attribute)

### ISSUE THREAD

**Issue by flipy** [patrickpollet/moodle_local_ldap#8]
The plugins is not finding any relation between users in LDAP and users in Moodle when searching for an attribute value to match.

Example:
processing cohort HR
looking for (&(&(samaccountname=*)(objectClass=user))(department=HR))
found 7 matching users in LDAP
found 0 matching users known to Moodle

Searching the LDAP with the same attributes as the plugin does, returns the list of users that should be imported into the cohort.

Any hint?

Thanks

**Comment by patrickpollet** [comment]
You have the classical problem with AD where attribute name is in mixed case samaccountname != sAMAccountName
It does not affect user search when logging into in Moodle but does affect user matching with this script

 Please see the doc on the wiki to fix it :

Cheers

Real user class : In Moodle, user class defined for LDAP or CAS authentication can be in lower case or mixed case, since LDAP search as case insensitive ; however when members of groups are listed in LDAP, it is quite common to see the user DN with class in mixed case , for example sAMAccountName=jdoe,ou=students,dc=... If the script does create cohorts but do not add any members to it, you may consider setting this value to the correct case ; alternatively, you may modify the user class in CAS/LDAP settings to match the exact case.

**Comment by flipy** [comment]
Thanks, the key was the "Real user class".
Even if not using LDAP Groups, the parameter that is being read is "Real user class" instead of "User class" in LDAP Attributes parameters.
